Support batch jsonrpc http requests
0xPolygon/polygon-edge pull request #106
Opened 2021-07-29 14:21 UTC by dankostiuk

# Description

Added support to handle batch JSON-RPC requests to align more closely with JSON-RPC support of geth (https://ethereum.org/en/developers/docs/apis/json-rpc/#json-rpc-support), iterating and dispatching each request in sequence for now. Also added more logging to log the request and response bodies.

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [ ] I have assigned this PR to myself
- [ ] I have added at least 1 reviewer
- [x] I have tested this code
- [ ] I have updated the README and other relevant documents (guides...)
- [x] I have added sufficient documentation both in code, as well as in the READMEs

2021-08-03 11:15 UTC, lazartravica requested changes
Congratulations on your first PR! I'd just kindly ask you to extend the tests a bit to cover the trimming functionality and that's it!

2021-08-03 11:15 UTC, lazartravica commented on jsonrpc/dispatcher_test.go
> +    {"id":1,"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x1", true]},
Please add a` \t\r\n` and a whitespace to the beginning of the test case byte slice to make sure that we properly strip as per https://www.ietf.org/rfc/rfc4627.txt

2021-08-03 16:21 UTC, dankostiuk commented on jsonrpc/dispatcher_test.go
> +    {"id":1,"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x1", true]},
Done. Thanks @lazartravica

2021-08-03 17:10 UTC, Vuksan reviewed
Thanks for helping out! 🙏 
Left a couple of questions

2021-08-03 17:10 UTC, Vuksan commented on jsonrpc/jsonrpc.go
> +	j.logger.Debug("handle", "request", newStr)
Why not just this?
```suggestion
	j.logger.Debug("handle", "request", string(data))
```

2021-08-03 17:10 UTC, Vuksan commented on jsonrpc/dispatcher.go
> +			d.logger.Debug("failed to dispatch", "method", "batch method", "err", err)
Call `internalError` instead?
```suggestion
			d.internalError("batch method", err)
```

2021-08-03 17:10 UTC, Vuksan commented on jsonrpc/dispatcher.go
> +			d.logger.Debug("failed to dispatch", "method", "batch method", "err", err)
Call `internalError` instead?
```suggestion
			d.internalError("batch method", err)
```

2021-08-04 08:53 UTC, Kourin1996 approved these changes
Looks good to me 👏 I tested it locally and it works completely. I'm grateful for your nice improvements.

2021-08-04 09:31 UTC, lazartravica approved these changes
💯 👍

2021-08-04 11:17 UTC, Vuksan approved these changes
🎉

2021-08-04 12:43 UTC, merged