EVM-495 AA - Relay transactions from the pool
0xPolygon/polygon-edge pull request #1269
Opened 2023-03-06 10:57 UTC by igorcrevar

# Description

In this task there will be implemented two things:
- pool of sorted transactions
- service which will relay tx from the pool to the actual node 

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [X] I have assigned this PR to myself
- [ ] I have added at least 1 reviewer
- [X] I have added the relevant labels
- [ ] I have updated the official documentation
- [ ] I have added sufficient documentation in code

## Testing

- [X] I have tested this code with the official test suite
- [ ] I have tested this code manually

### Manual tests

Please complete this section if you ran manual tests for this functionality, otherwise delete it

2023-03-13 13:48 UTC, ferranbt requested changes

2023-03-13 13:48 UTC, ferranbt commented on command/aarelayer/service/aa_relayer_service.go
> +	recipt, err := rs.txRelayer.WaitForReceipt(ctx, hash)
At this point, the relayer is only an abstraction to send a transaction (`SendTransactionWithoutReceipt`) and wait for the receipt (`WaitForReceipt`). You are not leveraging the utilities of the relayer (i.e. fire and forget the execution of a transaction). Thus, you can use directly the `jsonrpc.Client` package to send and wait for the receipt without complicating the `txrelayer`.

2023-03-13 18:23 UTC, igorcrevar commented on command/aarelayer/service/aa_relayer_service.go
> +	recipt, err := rs.txRelayer.WaitForReceipt(ctx, hash)
Fixed https://github.com/0xPolygon/polygon-edge/pull/1269/commits/c3a0bc274da59b886131b859103a8e06f894ce7d

2023-03-15 11:43 UTC, ferranbt approved these changes

2023-03-15 12:49 UTC, Nemanja0x approved these changes

2023-03-15 14:56 UTC, merged