IBFT PoS v3 tests port
0xPolygon/polygon-edge pull request #149
Opened 2021-09-09 15:35 UTC by zivkovicmilos

# Description

This PR is meant to port over tests from the `ibft-pos-v2` and `ibft-pos` branches, as well as add further support for querying / adding new tests.

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have tested this code
- [ ] I have updated the README and other relevant documents (guides...)
- [x] I have added sufficient documentation both in code, as well as in the READMEs

2021-09-15 06:58 UTC, lazartravica requested changes
Excellent job @zivkovicmilos ! I'd just ask you to please add a constraint for the epoch size so that it cannot be less than 2.

2021-09-15 09:22 UTC, zivkovicmilos commented
@lazartravica 
Good catch 💯 

I've added the constraint, as well as a brief explanation as to why it exists 👍 

971e3fd

2021-09-17 08:38 UTC, lazartravica approved these changes

2021-09-17 10:12 UTC, Kourin1996 approved these changes
LGTM 👌

2021-12-04 12:05 UTC, merged