evm-595-Reject future blocks
0xPolygon/polygon-edge pull request #1509
Opened 2023-05-15 13:52 UTC by Nemanja0x

# Description

The PR add validations for header in validationHeaderFields. Changes includes check for future block, whitch includes checking if the timestamp is within predefined time slot  of time.Now().UTC().Unix(). If not, we assume that it is a future block and reject it

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

Please complete this section if any breaking changes have been made, otherwise delete it

# Checklist

- [ ] I have assigned this PR to myself
- [ ] I have added at least 1 reviewer
- [ ] I have added the relevant labels
- [ ] I have updated the official documentation
- [ ] I have added sufficient documentation in code

## Testing

- [ ] I have tested this code with the official test suite
- [ ] I have tested this code manually

### Manual tests

Please complete this section if you ran manual tests for this functionality, otherwise delete it

# Documentation update

Please link the documentation update PR in this section if it's present, otherwise delete it

# Additional comments

Please post additional comments in this section if you have them, otherwise delete it

2023-05-17 10:56 UTC, stana-miric commented on consensus/polybft/polybft_config.go
> +	BlockTimeDrift int64
I suppose that negative values are not allowed? If that is the case should be uint64, also it would be nice to add a comment explaining the purpose of this configuration. This parameter is not supposed to be exposed in genesis file?

2023-05-17 10:56 UTC, goran-ethernal commented on consensus/polybft/polybft_config.go
> +	BlockTimeDrift int64
```suggestion
	BlockTimeDrift int64 `json:blockTimeDrift`
```

2023-05-17 10:56 UTC, goran-ethernal commented on consensus/polybft/polybft_config.go
> +	// hardcoded for now
```suggestion
	// hardcoded until we implement on-governance
```

2023-05-17 10:58 UTC, goran-ethernal requested changes
I think we should add a flag to the `genesis` command as well. Even though we will have this parameter as a part of on-chain governance soon, for the first start of the chain, we need to specify it in the `genesis`.

2023-05-17 11:04 UTC, stana-miric approved these changes

2023-05-17 11:51 UTC, Stefan-Ethernal reviewed
Agree with @goran-ethernal and @stana-miric:
- `BlockTimeDrift` should be `uint64`, and
- a flag should be exposed in the genesis command in order to configure it initially.

Also, 2 out of 3 tests in the `TestE2E_Consensus_Basic_WithNonValidators` test are failing (the ones which are restarting nodes and letting them sync). I haven't realized why exactly, but have seen this error message in basically all of the validator nodes:

```go
2023-05-17T09:29:38.694Z [DEBUG] polygon.server.polybft.consensus_runtime: HasQuorum has been called but proposer could not be retrieved: error="get latest proposer not found - height: 14, round: 3, pc height: 14, pc round: 0"
```

2023-05-25 10:56 UTC, goran-ethernal approved these changes

2023-05-25 11:38 UTC, Stefan-Ethernal approved these changes

2023-05-25 11:38 UTC, Stefan-Ethernal commented on command/genesis/genesis.go
> +			"configuration for block time drift value",
It is in seconds right? Anyways, think that it is wise to specify it flag description.
```suggestion
			"configuration for block time drift value (in seconds)",
```

2023-05-25 11:38 UTC, Stefan-Ethernal commented on consensus/polybft/polybft_config.go
> +	BlockTimeDrift uint64 `json:"blockTimeDrift"`
Please add a comment here, which explains what `BlockTimeDrift` is.

2023-05-25 11:38 UTC, Stefan-Ethernal commented on consensus/polybft/fsm.go
> +		return fmt.Errorf("block from the future. block time: %d, time drift %d", header.Timestamp, blockTimeDrift)
```suggestion
		return fmt.Errorf("block from the future. block timestamp: %d, configured block time drift %d seconds", header.Timestamp, blockTimeDrift)
```

Also thinking out loud: should we convert `header.Timestamp` into a proper time format and report it that way in an error message, instead of logging (raw) elapsed seconds? The mindset is that the log message would contain time stamp in date/time format, so it would be maybe easier figuring out what is going on.

2023-05-25 13:02 UTC, jelacamarko commented on consensus/polybft/fsm.go
> +		return fmt.Errorf("block from the future. block time: %d, time drift %d", header.Timestamp, blockTimeDrift)
I agree. I will change that also.

2023-05-26 08:26 UTC, Stefan-Ethernal approved these changes

2023-05-26 09:33 UTC, merged