modified txRelayer to fetch gasprice from current eth client instead of hardcoded one
0xPolygon/polygon-edge pull request #1552
Opened 2023-05-26 01:41 UTC by adirola

# Description

This PR fixes the https://github.com/0xPolygon/polygon-edge/issues/1551 with rootchain deploy command when the rootchain is not locally deployed geth instance. If the "private-key" flag is set, then fetch the gasPrice limit using etc client. Otherwise, all transaction will go with default hardcoded value of gasLimit, which will only work with geth instance.

# Changes include

- [x ] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x ] I have assigned this PR to myself
- [ ] I have added at least 1 reviewer
- [ ] I have added the relevant labels
- [ ] I have updated the official documentation
- [ ] I have added sufficient documentation in code

## Testing

- [ ] I have tested this code with the official test suite
- [x ] I have tested this code manually

### Manual tests

I have manually tested the code and successfully deployed the contracts on both Polygon POS and Polygon Mumbai

2023-05-26 01:46 UTC, adirola commented
recheck

2023-05-26 01:49 UTC, adirola commented
Hi @goran-ethernal @Stefan-Ethernal, I found this issue while using the root chain fund command can you help me raise this PR for the same

2023-05-26 01:50 UTC, adirola commented
I have read the CLA Document and I hereby sign the CLA

2023-05-26 06:35 UTC, igorcrevar commented on txrelayer/txrelayer.go
> -		txn.GasPrice = DefaultGasPrice
retrieve gas price only `if txn.GasPrice == 0` 
```
if txn.GasPrice == 0 {
        gasPrice, err := t.Client().Eth().GasPrice()
	if err != nil {
		return ethgo.ZeroHash, err
	}
	
	txn.GasPrice = gasPrice
}
```

2023-05-26 07:23 UTC, Stefan-Ethernal approved these changes
Aside from @igorcrevar comment, LGTM.

2023-05-26 10:44 UTC, adirola commented
addressed the issue raised by @igorcrevar . Updated the PR according to same.

2023-05-26 10:45 UTC, goran-ethernal approved these changes

2023-05-26 12:34 UTC, Stefan-Ethernal commented
@adirola also it probably makes sense to find all references of `TxRelayer.SendTransaction` and remove the explicitly setting of `GasPrice` there and let tx relayer to this instead. WDYT?

2023-05-26 15:59 UTC, adirola commented
I have read the CLA Document and I hereby sign the CLA

2023-05-26 16:24 UTC, adirola commented
@Stefan-Ethernal I have fixed the lint error, it does sound better to change all references of TxRelayer.SendTransaction and remove the explicit setting of GasPrice from the outside and let tx relayer.
Should we do it in this PR or a new PR please advise.

2023-05-26 21:12 UTC, Stefan-Ethernal commented
> @Stefan-Ethernal I have fixed the lint error, it does sound better to change all references of TxRelayer.SendTransaction and remove the explicit setting of GasPrice from the outside and let tx relayer do it.
> Should we do it in this PR or a new PR please advise.

I’d say let’s do it through this one if you don’t mind.

2023-05-27 17:52 UTC, igorcrevar approved these changes

2023-05-29 11:17 UTC, Stefan-Ethernal requested changes
https://github.com/0xPolygon/polygon-edge/pull/1552#issuecomment-1564324473

2023-06-06 08:35 UTC, dusan-maksimovic commented
Work on this will be continued through the [new](https://github.com/0xPolygon/polygon-edge/pull/1589) PR.

2023-06-06 08:39 UTC, Stefan-Ethernal commented
> Work on this will be continued through the [new](https://github.com/0xPolygon/polygon-edge/pull/1589) PR.

Closing this PR per above comment.

2023-06-06 08:39 UTC, closed without merging