Add total size limit in TxPool
0xPolygon/polygon-edge pull request #168
Opened 2021-09-29 07:18 UTC by Kourin1996

# Description

Please provide a detailed description of what was done in this PR

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

Please complete this section if any breaking changes have been made, otherwise delete it

# Checklist

- [ ] I have assigned this PR to myself
- [ ] I have added at least 1 reviewer
- [ ] I have tested this code
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

# Additional comments

Please post additional comments in this section if you have them, otherwise delete it

2021-10-06 19:50 UTC, zivkovicmilos commented on command/helper/helper.go
> +	DefaultPriceLimit     = 1
Why would the default value be `1?`

2021-10-06 19:51 UTC, zivkovicmilos commented on e2e/framework/testserver.go
> +		args = append(args, "--price-limit", strconv.FormatUint(*t.Config.PriceLimit, 10))
What do you think about adding support for this value to be passed in as either a decimal or a hex value?

2021-10-13 07:07 UTC, Kourin1996 commented on e2e/framework/testserver.go
> +		args = append(args, "--price-limit", strconv.FormatUint(*t.Config.PriceLimit, 10))
Actually we should discuss about this in https://github.com/0xPolygon/polygon-sdk/pull/151.
I think it's good idea. I will do there

2021-10-13 07:09 UTC, Kourin1996 commented on command/helper/helper.go
> +	DefaultPriceLimit     = 1
Actually we should discuss about this in https://github.com/0xPolygon/polygon-sdk/pull/151
In order to block tx with 0 gas price via gossip

2021-10-13 15:14 UTC, zivkovicmilos commented on command/helper/helper.go
> +	DefaultPriceLimit     = 1
Got it, thank you for clarifying 👍

2021-10-13 15:15 UTC, zivkovicmilos approved these changes
Thank you for clearing up the questions I've had 🙏 

Good to go 🚀

2021-10-27 17:38 UTC, lazartravica requested changes
Excellent work @Kourin1996 

Just 2 more requirements:

- You are lacking test cases for adding local transactions and discarding remote ones 
- We need a corresponding PR in the https://github.com/0xPolygon/polygon-sdk-docs/

2021-10-29 12:25 UTC, Kourin1996 commented
Doc PR: https://github.com/0xPolygon/polygon-sdk-docs/pull/18

2021-10-29 12:48 UTC, Kourin1996 commented
> You are lacking test cases for adding local transactions and discarding remote ones

Added at https://github.com/0xPolygon/polygon-sdk/pull/168/commits/bc681d8e091b6bd4d35aad9209f9967a2417d98c

2021-11-01 13:02 UTC, lazartravica commented
@Kourin1996 There are merge conflicts that popped up since we are using squash & merge on the repository.

I suggest that next time you open a PR with the target branch set to the one that you have the dependency on, and not develop so that it's easier for you.

Thank you!

2021-11-01 13:02 UTC, lazartravica approved these changes
👌 please resolve the merge conflicts and we are good to go (there are merge conflicts on the docs repo as well).

2021-11-02 14:19 UTC, merged