Extend the genesis command to allow a configurable block gas limit
0xPolygon/polygon-edge pull request #173
Opened 2021-10-05 12:00 UTC by PtitLuca

# Description

Please provide a detailed description of what was done in this PR
This PR extends the genesis command flags by adding a `--blockLimit` parameter which will be included in the `genesis.json` file.

It includes tests for a user-defined limit and the default one.

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [ ] I have assigned this PR to myself
- [ ] I have added at least 1 reviewer
- [X] I have tested this code
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

2021-10-06 15:25 UTC, lazartravica requested changes
Excellent job @PtitLuca! 

I think this is the perfect time to get acquainted with our e2e testing framework for spinning up Test Servers with custom configurations.

Please take a look at the comments. 🤘

2021-10-06 15:25 UTC, lazartravica commented on command/genesis/genesis.go
> +	c.FlagMap["blockLimit"] = helper.FlagDescriptor{
All CLI arguments we have are `snake-case`, change this to `block-limit`

2021-10-06 15:25 UTC, lazartravica commented on command/genesis/genesis_test.go
> +package genesis_test
Although your test is completely correct, it's too much code just to check that our code is writting JSON files correctly, in general we want to test the entire implications of running a command and not just the immediate result (notice how none of the subdirectories under `command/` have any `*_test.go` files). 

A test that I think would make much more sense is a full on e2e test. You can take a look at [TestPreminedBalance](https://github.com/0xPolygon/polygon-sdk/blob/96be90487c144f7b1589ac65aad3f741c81644e3/e2e/transaction_test.go#L56-L103).

What I encourage you to try to do is to create a test which will setup the TestServer (just as in the above linked test), call the JSON-RPC getBlockByNumber method for the genesis block and assert that the gasLimit is what you expect it to be.

2021-10-06 19:38 UTC, zivkovicmilos commented on command/genesis/genesis_test.go
> +package genesis_test
I think it's clever that he wrote out the command output to the file and later checked it. 
We should probably keep it now that it's written out, but add the e2e test that you've mentioned 👍 

One thing I'd change is to just place these generated files in a sub-directory that makes it clear it was not a part of the original codebase, but just a result of the tests, for example `genesis-tests/genesis.json`

2021-10-06 19:39 UTC, zivkovicmilos approved these changes
Lookin' good 💯 

Please check out @lazartravica's comments regarding the tests.

2021-10-12 04:43 UTC, Kourin1996 reviewed
Hi, Thank you for the PR! I have noticed 2 things and It'd be great if you could check them.

(1) dev command has similar command option with different name.
When you run node with dev mode, you don't have to run `genesis` command before node starts. In this case, genesis.json will be created automatically if it doesn't exist. `dev` command supports `gas-limit` option already. I think we can unify the option names.

(2) Block Gas Limit is not set is subsequent blocks.
When you give `--block-gas-limit` option on genesis command, block gas limit in genesis.json and genesis block change. But blocks from 1 are still using `100000000` due to hardcoded value in `buildBlock` in consensus/ibft.go or `writeNewBlock` in consensus/dev.go. A block gas limit adjustment would be another task but I think you can inherit parent's block gas limit for now.

2021-10-13 06:59 UTC, Kourin1996 approved these changes
Thank you for fixing. Looks good to me 👌

2021-10-15 16:17 UTC, lazartravica commented on command/genesis/genesis.go
> +	c.FlagMap["blockLimit"] = helper.FlagDescriptor{
@PtitLuca thanks for the fix. Please include the commit hash in the comment to the requested change, it's way easier to keep track of what and why was changed that way.

Thanks

2021-10-15 16:21 UTC, lazartravica approved these changes
Excellent job Luca!

Congratulations on your first ready-to-merge PR :)

Feel free to merge.

Keep it coming 🤘

2021-10-21 12:37 UTC, merged