Add basic stress test txns
0xPolygon/polygon-edge pull request #177
Opened 2021-10-06 17:24 UTC by zivkovicmilos

# Description

This PR just adds 2 simple tests that stress test the consensus module.

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have tested this code
- [ ] I have updated the README and other relevant documents (guides...)
- [x] I have added sufficient documentation both in code, as well as in the READMEs

2021-10-06 23:37 UTC, Kourin1996 requested changes

2021-10-06 23:37 UTC, Kourin1996 commented on e2e/StressTest.sol
> +import "hardhat/console.sol";
It should work without this import

2021-10-06 23:37 UTC, Kourin1996 commented on e2e/transaction_test.go
> +func Test_TransactionDevLoop(t *testing.T) {
Is it possible to share a part of codes with `Test_TransactionIBFTLoop`?

2021-10-08 11:43 UTC, zivkovicmilos commented on e2e/StressTest.sol
> +import "hardhat/console.sol";
Got it, thank you for pointing it out 👍 

65759db

2021-10-08 11:55 UTC, zivkovicmilos commented on e2e/transaction_test.go
> +func Test_TransactionDevLoop(t *testing.T) {
Yep, fixed 👍 

4e257ee

2021-10-12 06:06 UTC, Kourin1996 approved these changes
LGTM 👍

2021-11-01 13:14 UTC, lazartravica approved these changes
👌

2021-11-02 18:03 UTC, merged