TxPool gas limit verification + txn error recover
0xPolygon/polygon-edge pull request #183
Opened 2021-10-14 15:52 UTC by 0xpanoramix

# Description

This PR resolves #174 .

It adds two features :

1. A new verification whenever a transaction is submitted to the transaction pool operator.
2. Any detected error while writing transaction to a block is now marked as recoverable or not recoverable, indicating if the transaction has to be discarded or not. 

# Changes include

- [X] Bugfix (non-breaking change that solves an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [X] I have assigned this PR to myself
- [X] I have added at least 1 reviewer
- [X] I have tested this code
- [ ] I have updated the README and other relevant documents (guides...)
- [X] I have added sufficient documentation both in code, as well as in the READMEs

2021-10-22 04:30 UTC, Kourin1996 requested changes
Hi, Thank you for the PR. I've left small comments. I'd appreciate if you could check and fix if need. Thanks.

2021-10-22 04:30 UTC, Kourin1996 commented on state/executor.go
> +		}
Just confirm. Why this is not recoverable? This error happens if you can't add this tx to block because block doesn't have enough remaining gas to take this tx. So I thought you could add this tx in next block.

Did you want to check if tx gas doesn't exceed BlockGasLimit?

2021-10-22 04:30 UTC, Kourin1996 commented on txpool/txpool.go
> +	txnsQueue.nextNonce -= 1
you might want to check if accountQueues has record for tx.From just in case

2021-10-22 08:36 UTC, 0xpanoramix commented on state/executor.go
> +		}
> Did you want to check if tx gas doesn't exceed BlockGasLimit ?

Exactly, if the block has a gas limit of 5, and the gas provided in the message is 6, it will never be able to fit in a block.
This check is a special case of the third check (`the amount of gas required is available in the block`).

2021-10-22 15:32 UTC, Kourin1996 commented on state/executor.go
> +		}
Please note that t.gasPool doesn't equal to BlockGasLimit. If some transactions are processed already, t.gasPool has consumed the total of used gas already.

2021-10-25 09:38 UTC, zivkovicmilos commented on e2e/txpool_test.go
> +func TestInvalidTransactionRecover(t *testing.T) {
Would love to see a description / test scenario above this test 🙏

2021-10-25 09:40 UTC, zivkovicmilos commented on state/executor.go
> +type TransactionApplicationError struct {
What do you think about renaming this to `TransitionApplicationError`, since it applies to state transitions instead of just regular transactions?

@Kourin1996 @lazartravica @Vuksan

2021-10-25 09:41 UTC, zivkovicmilos commented on state/executor.go
> +	ErrBlockLimitExceeded     = fmt.Errorf("specified gas exceed block gas limit")
Typo here, should be `exceeds`

2021-10-25 09:44 UTC, zivkovicmilos commented on txpool/txpool.go
> +	if t.accountQueues[tx.From] != nil {
Please note that this should be thread safe after we merge PR #178

2021-10-25 09:45 UTC, zivkovicmilos commented on state/executor.go
> +			}
I see that we repeat this construction logic a lot of times when returning.

What do you think about separating it out into a small helper function like `generateTransitionErr`, or something along those lines?

2021-10-25 09:45 UTC, zivkovicmilos requested changes
Looks alright so far 👍 
Excellent work on the tests 💯 

Left a few comments we should discuss

2021-10-26 03:09 UTC, Kourin1996 commented on state/executor.go
> +type TransactionApplicationError struct {
Agree with @zivkovicmilos's idea

2021-10-27 15:48 UTC, 0xpanoramix commented on state/executor.go
> +		}
Thank you for reporting the error, I've moved this verification outside the apply function since I don't have access to the block gas limit inside of it.
It is now in the `writeNewBlock` function in https://github.com/0xPolygon/polygon-sdk/pull/183/commits/ecd78d43b1ef64d0357f50ed924f89b926f5f6bc.

2021-10-27 15:50 UTC, 0xpanoramix commented on txpool/txpool.go
> +	if t.accountQueues[tx.From] != nil {
Good to know, thank you !

2021-10-28 09:56 UTC, Kourin1996 commented on state/executor.go
> +	IsRecoverable	bool // Should the transaction be discarded, or put back in the queue.
I think you can format this parr

2021-10-28 09:56 UTC, Kourin1996 commented on consensus/ibft/ibft.go
> +			i.txpool.DecreaseAccountNonce(txn)
Just confirm. You don't need to put tx back in this case?

2021-10-28 10:45 UTC, 0xpanoramix commented on e2e/txpool_test.go
> +func TestInvalidTransactionRecover(t *testing.T) {
Added in https://github.com/0xPolygon/polygon-sdk/pull/183/commits/041dac89638041f72990dd1db784ba4a74b498cf

2021-10-28 10:45 UTC, 0xpanoramix commented on state/executor.go
> +type TransactionApplicationError struct {
Added in https://github.com/0xPolygon/polygon-sdk/pull/183/commits/1c2736e2686c3503d22ac12cc23a9206a4c28066

2021-10-28 10:46 UTC, 0xpanoramix commented on state/executor.go
> +	ErrBlockLimitExceeded     = fmt.Errorf("specified gas exceed block gas limit")
Fixed in https://github.com/0xPolygon/polygon-sdk/pull/183/commits/081f3c0feb45ed866bc62681f88479ced7fdc1f0

2021-10-28 16:15 UTC, 0xpanoramix commented on state/executor.go
> +			}
Added in https://github.com/0xPolygon/polygon-sdk/pull/183/commits/1c2736e2686c3503d22ac12cc23a9206a4c28066

2021-10-28 16:17 UTC, zivkovicmilos approved these changes
Thank you for resolving these mini changes 🙏 

Good to go 🚀

2021-10-28 16:20 UTC, 0xpanoramix commented on state/executor.go
> +	IsRecoverable	bool // Should the transaction be discarded, or put back in the queue.
Fixed in https://github.com/0xPolygon/polygon-sdk/pull/183/commits/56679fcc33ff00437b754ddeeeabab08d1a94787

2021-10-28 16:26 UTC, Kourin1996 approved these changes
LGTM 👏

2021-10-28 16:33 UTC, lazartravica approved these changes
Well done @PtitLuca 

I love this pattern with recoverable/unrecoverable errors an I'm glad the tests are easy to read as well.

🤘

2021-10-28 17:08 UTC, merged