Fix/peer reconnection
0xPolygon/polygon-edge pull request #186
Opened 2021-10-18 07:41 UTC by munna0908

# Description

This PR fixes the issue that the non bootnodes keep disconnected after loosing all connections. 
As part of this change, every node initiates a new routine which periodically(Every 30 sec)attempts to make new connection, if peercount is less than the minimumPeercount (currently set to 1 )

# Changes include

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have tested this code
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

2021-10-19 05:53 UTC, Kourin1996 requested changes
Hello, Thank you for the PR. I've left some comments. It'd be great if you could check and fix if need. Thanks!

2021-10-19 05:53 UTC, Kourin1996 commented on network/server_test.go
> +func WaitUntilPeerReconnects(ctx context.Context, srv *Server, id peer.ID) (bool, error) {
I think `WaitUntilPeerConnectsTo` is better? because you don't check node disconnects from some peer in this function.

2021-10-19 05:53 UTC, Kourin1996 commented on protocol/syncer.go
> +			}
`handler` may expect a block, so I think you shouldn't pass nil to handler. So you might want to break if popBlock returns nil

2021-10-19 05:53 UTC, Kourin1996 commented on network/server.go
> +		case <-time.After(30 * time.Second):
I'm sure polling approach will work. So it's just curious question => is it possible for us to use any Event Subscription? But PeerEventDisconnected is emitted before peers is deleted from store. So we may add new event?

I want some comments about this, @lazartravica

2021-10-19 07:52 UTC, Kourin1996 commented on protocol/syncer.go
> +			}
@munna0908 and me talked outside. I think we can pass nil to handler. But we do double check if peer is closed or not in WatchSyncWithPeer and popBlock. Can we skip p.IsClosed() in `WatchSyncWithPeer`? In this case, you modify handler little bit: if block is nill then handler return false

2021-10-19 10:26 UTC, lazartravica requested changes
Please see my comments.

2021-10-19 10:26 UTC, lazartravica commented on protocol/syncer.go
> +			}
I agree with @Kourin1996's comments, we can skip the first `if p.IsClosed() {` in the `WatchSyncWithPeer`, and rely on the existing check in `popBlock` and add a new one to the `handler`.

@munna0908 could you also please refactor so that the callback is not called `handler` but rather `isValidator`, and avoid the double negation that we have (`return !isValidator` and `if !handler(b)`)?

2021-10-19 10:26 UTC, lazartravica commented on network/server.go
> +		case <-time.After(30 * time.Second):
@munna0908 the `checkPeerConnections` can block on receiving the `PeerEventDisconnected` event and only after that check if the `s.numPeers() < MinimumPeerConnections` and try to reconnect to the bootnode.

Feel free to create a new subscription. 

Also, if you have any concerns about this (you mentioned offline somethng among the lines of cascading events) => could you care to explain how that might happen and what would be the result?

TLDR: Polling every 30 seconds is something that we should try to avoid since we have a straightforward way of subscribng to events.

2021-10-19 15:55 UTC, munna0908 commented on protocol/syncer.go
> +			}
@lazartravica current implementation of pop block, blocks until we receive a block, but it's not safe to indefinitely wait for a block from remote node, because the remote node may be malicious. 
So in this [PR](https://github.com/0xPolygon/polygon-sdk/pull/181/commits/fbc80d4703080fd00a189c2d30c9ccaf0a5f8701) @Kourin1996  added a timeout, and he is returning a nil value, so i felt having an explict check i.e p.isClose() is required. 
Looking forward to your inputs.

2021-10-19 15:56 UTC, munna0908 commented on protocol/syncer.go
> +			}
@lazartravica sure will refactor handler callback func

2021-10-20 06:52 UTC, munna0908 commented on network/server.go
> +		case <-time.After(30 * time.Second):
Fixed it Commit-[Link](https://github.com/0xPolygon/polygon-sdk/pull/186/commits/efd124d6f9bff3282e598c556dbcb01e47429b62)

2021-10-20 06:53 UTC, munna0908 commented on network/server_test.go
> +func WaitUntilPeerReconnects(ctx context.Context, srv *Server, id peer.ID) (bool, error) {
@Kourin1996 Fixed it [link](https://github.com/0xPolygon/polygon-sdk/pull/186/commits/7d56b77aff6c6622aa530a9a7c47cbf686582e65)

2021-10-25 09:47 UTC, zivkovicmilos commented on network/server.go
> +					//TODO: dial peers from the peerstore
What's up with this TODO?

2021-10-25 09:48 UTC, zivkovicmilos commented on network/server.go
> +					s.dialQueue.add(s.discovery.bootnodes[rand.Intn(len(s.discovery.bootnodes))], 10)
Can we please separate this out into multiple lines, it's messy to read? 🙈

2021-10-25 09:50 UTC, zivkovicmilos commented on network/server_test.go
> +func TestPeerReconnection(t *testing.T) {
Please provide some kind of description / test scenario for this test 🙏

2021-10-25 09:52 UTC, zivkovicmilos requested changes
Looks good 💯 

Left minor comments that should be resolved

2021-10-26 03:53 UTC, munna0908 commented on network/server.go
> +					//TODO: dial peers from the peerstore
@lazartravica  suggested to create a new issue in youtrack which can be handled later.

2021-10-27 13:00 UTC, zivkovicmilos approved these changes
Thank you for the fixes 🙏 

Looks good 🚀

2021-10-28 12:07 UTC, lazartravica commented
We have discussed offline to bring back the polling approach without the events, to avoid code complexity.

2021-10-28 12:20 UTC, lazartravica commented on protocol/syncer.go
> +			}
Thanks Rahul, I agree with you. If @Kourin1996 is on the same line, he can resolve the conversation.

2021-10-31 10:28 UTC, munna0908 commented
> We have discussed offline to bring back the polling approach without the events, to avoid code complexity.

@lazartravica reverted back to polling approach here is the [link](https://github.com/0xPolygon/polygon-sdk/pull/186/commits/50554df7736c9ff8356abd3e3c3f897bd890dce2)

2021-11-02 11:14 UTC, lazartravica approved these changes
Just take a look at my minor nitpick and that's it, feel free to merge

2021-11-02 11:14 UTC, lazartravica commented on e2e/syncer_test.go
> +		//config.SetShowsLog(i == IBFTMinNodes+numNonValidators-1)
Please remove this comment, we already have a PR which removed it.

2021-11-02 16:49 UTC, Kourin1996 approved these changes
LGTM 👍

2021-11-03 06:48 UTC, munna0908 commented
@lazartravica 

> Just take a look at my minor nitpick and that's it, feel free to merge

Done

2021-11-07 17:33 UTC, merged