Enable txPool to accept sped up transactions
0xPolygon/polygon-edge pull request #188
Opened 2021-11-01 08:30 UTC by dbrajovic

# Description

Extend client functionality with the `--speed-up` flag indicating the minimum amount of additional gas price a new transaction is supposed to have in order to overwrite the previous one (same nonce).

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [ ] I have assigned this PR to myself
- [ ] I have added at least 1 reviewer
- [ ] I have tested this code
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

2021-11-03 19:37 UTC, lazartravica requested changes
Please create and link the corresponding sdk-docs repo PR.

2021-11-08 15:56 UTC, zivkovicmilos commented on command/server/server_command.go
> +		Description: "TODO",
Please add a more detailed description :)

2021-11-08 15:57 UTC, zivkovicmilos commented on server/server.go
> +		m.txpool, err = txpool.NewTxPool(logger,
Nitpick warning: Please put logger on a separate line as well, so it's more eye-pleasing

2021-11-18 13:24 UTC, dbrajovic commented
Closing this one in favour of [PR#220](https://github.com/0xPolygon/polygon-sdk/pull/220)

2021-11-18 13:24 UTC, closed without merging