Add the tx hash response to add txn operator call
0xPolygon/polygon-edge pull request #317
Opened 2021-12-27 18:44 UTC by zivkovicmilos

# Description

This PR adds support for a transaction hash response in the `txpool add` operator command.

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have tested this code
- [ ] I have updated the README and other relevant documents (guides...)
- [x] I have added sufficient documentation both in code, as well as in the READMEs

2021-12-28 09:40 UTC, Kourin1996 requested changes
https://github.com/0xPolygon/polygon-sdk/blob/779f2cf61c74c8a3ae45dd8099d75f8854d1e8ae/command/txpool/txpool_add.go#L201-L216

You might want to add hash in normal results.

2021-12-28 09:55 UTC, zivkovicmilos commented
> You might want to add hash in normal results. It looks ok apart from that.
> 
> https://github.com/0xPolygon/polygon-sdk/blob/779f2cf61c74c8a3ae45dd8099d75f8854d1e8ae/command/txpool/txpool_add.go#L201-L216

🤦 I completely forgot

Added:


de50d4f

2021-12-28 14:36 UTC, Kourin1996 approved these changes
Looks good 👍

2021-12-29 13:35 UTC, brkomir approved these changes

2021-12-29 14:26 UTC, dbrajovic approved these changes

2021-12-29 14:30 UTC, merged