Add CORS configuration to JSON-RPC
0xPolygon/polygon-edge pull request #321
Opened 2021-12-29 10:08 UTC by PtitLuca

# Description

This PR adds to following :

- You can now submit a cors configuration for the JSON-RPC server using a json file
- For now, allowed domains is the only field you can configure

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

Please complete this section if any breaking changes have been made, otherwise delete it

# Checklist

- [X] I have assigned this PR to myself
- [ ] I have added at least 1 reviewer
- [ ] I have tested this code
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

2021-12-29 16:12 UTC, zivkovicmilos approved these changes
Looks good to me 💯 

Please provide some steps on how to test this out in the PR description 🙏

2021-12-30 08:35 UTC, ferranbt commented on jsonrpc/jsonrpc.go
> +type Handlers struct {
Instead of creating a new struct, add this to the Config field, it is meant to add these type of configurations.

2021-12-30 08:40 UTC, ferranbt commented on server/config.go
> +	HandlersConfig *jsonrpc.Handlers
I think at this point it is not scalable to add more fields into the base Config struct. Instead, create a JsonRPC config struct that holds all the jsonrpc configuration: bind addr and handlers. Note that this is what we do in Telemetry.

2021-12-30 08:40 UTC, ferranbt commented on go.mod
> +	github.com/gorilla/handlers v1.5.1
You should be really mindful every time a new package is included into the codebase. Do we know how this package works? Have we vetted it in detail? Is it worth it to include two new packages just to enable Cors in the json-rpc package?

2021-12-30 08:40 UTC, ferranbt commented on command/helper/config.go
> +		handlers := &jsonrpc.Handlers{}
I have never seen including handlers from config file before.

2021-12-30 10:19 UTC, Kourin1996 reviewed
I'd like to give one suggestion and raise one discussion

(1) Enabling CORS
In principle, you need to set some fields in HTTP response header to enable CORS. As Ferran said, we don't need to add new package for CORS setting at the moment. You can create a `middleware` to write headers for CORS configuration

(2) CORS settings from json
CORS settings will be set at json file and program loads this if the path is given. I'm not sure the clear reasons why we will load CORS settings from json file. Even if user prefer to load CORS settings from JSON file, we have existing flags `--config` to load whole configuration from json file already. If you didn't have discussion about this before, let's discuss.

cc: @zivkovicmilos @lazartravica @brkomir

2022-01-01 21:48 UTC, iVerticalsInc approved these changes

2022-01-19 10:28 UTC, lazartravica requested changes
Let's not do this by including the Gorilla handlers package. 

As CORS is mainly a clientside thing, we can easily add new headers to the HTTP server.

2022-01-19 12:04 UTC, closed without merging