[WIP] Refactor e2e test
0xPolygon/polygon-edge pull request #52
Opened 2021-06-04 13:48 UTC by Kourin1996

# Description

This PR aims to remove some dependencies from e2e test. It eliminates pre-requirements for e2e and enables to run them with a clean environment and same conditions.
- Stop using solc (solidity compiler) in e2e test
- Run new clean IBFT nodes internally in every test instead of IBFT nodes running locally

# Changes include

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

Please complete this section if any breaking changes have been made, otherwise delete it

# Checklist

- [ ] I have assigned this PR to myself
- [ ] I have added at least 1 reviewer
- [ ] I have tested this code
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

# Additional comments

Please post additional comments in this section if you have them, otherwise delete it

2021-06-08 07:55 UTC, lazartravica requested changes
Excellent job!

All tests are passing except `TestBroadcast:tx_should_not_reach_to_last_node`.

@Kourin1996 is it the same on your end?

2021-06-08 07:55 UTC, lazartravica commented on e2e/README.md
> +```
Thank you for the docs! @Kourin1996  🙏

2021-06-11 14:01 UTC, Vuksan requested changes
Great work @Kourin1996 ! 🚀 
I have several observations - nothing major, mostly small things.

2021-06-11 14:01 UTC, Vuksan commented on e2e/README.md
> +$ solc --bin e2e/sample.sol
Can you please add the version of the compiler you used as well.
I have tried the command with this compiler and it fails:
```
0.7.1+commit.f4a555be.Darwin.appleclang
```

2021-06-11 14:01 UTC, Vuksan commented on e2e/framework/config.go
> +// SetIBFTDirPrefix callback sets prefix of IBFT directories
Wrong comment, probably c/p from previous method

2021-06-11 14:01 UTC, Vuksan commented on e2e/framework/config.go
> +// SetBootnodes sets bootnodes
Wrong comment, probably c/p from previous method

2021-06-11 14:01 UTC, Vuksan commented on e2e/framework/helper.go
> +			time.Sleep(time.Second)
Why the Sleep()?

2021-06-11 14:01 UTC, Vuksan commented on e2e/discovery_test.go
> +		}
Shouldn't this `conf` initialization be outside the for loop?

2021-06-11 14:01 UTC, Vuksan commented on e2e/discovery_test.go
>  				}
Shouldn't the message in the if block be "should know", and before the if block "shouldn't know"?
If I understand the tests, first 4 nodes should know each other, and not the other way around.

2021-06-11 14:01 UTC, Vuksan commented on e2e/broadcast_test.go
> +			}
I see that this is repeated through some tests... what do you think about extracting it to a helper function for tests?

[from line 40 to 75, in case this github selector bugs out]

2021-06-11 14:01 UTC, Vuksan commented on e2e/logs_test.go
> +	assert.GreaterOrEqual(t, len(res), numCalls/2)
Just to check, you didn't forget about this todo?
I noticed that test doesn't receive all filter changes, but most of them.

2021-06-11 14:01 UTC, Vuksan commented on e2e/logs_test.go
> +	}
The code (ln74-98) seems to be the same as in the previous test. Is it possible to extract it in a helper function?

2021-06-11 14:01 UTC, Vuksan commented on e2e/logs_test.go
> -
I just noticed that at the end of this test we have `fmt.Println()` instead of `assert`.
Maybe just assert if 3 changes occurred?

2021-06-11 14:01 UTC, Vuksan commented on e2e/ibft_test.go
>  	for i := 0; i < 3; i++ {
```suggestion
	for i := 0; i < IBFTMinNodes - 1; i++ {
```

2021-06-11 14:01 UTC, Vuksan commented on e2e/ibft_test.go
> +		assert.NotNil(t, receipt)
Maybe add additional check, to make sure it is the same transaction:
```suggestion
		assert.NotNil(t, receipt)
		assert.Equal(t, receipt.TransactionHash, hash)
```

2021-06-11 14:01 UTC, Vuksan commented on e2e/transaction_test.go
> +	key, err := wallet.GenerateKey()
Just curious - why not `framework.GenerateKeyAndAddr(t)` as in other tests?

2021-06-11 14:01 UTC, Vuksan commented on e2e/transaction_test.go
> +		srv.WaitForReceipt(ctx, hash)
To add some checks

```suggestion
		srv.WaitForReceipt(ctx, hash)
		
		assert.NoError(t, err)
		assert.NotNil(t, receipt)
		assert.Equal(t, receipt.TransactionHash, hash)
```

2021-06-11 14:01 UTC, Vuksan commented on e2e/transaction_test.go
>  	}
I have an issue with this test, since we aren't actually asserting the third case, since there `testCase.shouldFail` is `true`.

- If the expected behavior should be that for the nonexisting account we should get an error, we should append the latest if with the following code and then the test will fail, since it doesn't return the error, but we expect it to (or at least that seems to me).
```
 else {
     assert.NotNil(t, err)
}
```

- However, if the expected behaviour should be that for "nonexistent" account we should get a 0 balance, then we should change the test to reflect  that.

I am in favour of the second approach, since there are no "nonexistent" accounts if you ask me - any valid address is an existing account.

2021-06-11 14:01 UTC, Vuksan commented on e2e/transaction_test.go
>  	}
We can open another task for this, it doesn't have to be solved in this PR, just wanted to discuss.

2021-06-11 14:01 UTC, Vuksan commented on e2e/transaction_test.go
>  			true,
This case is never asserted in tests. We can add a task to cover that.

2021-06-11 14:01 UTC, Vuksan commented on e2e/transaction_test.go
>  			// ACC #2 -> ACC #1
```suggestion
			// ACC #3 -> ACC #2
```

2021-06-11 15:13 UTC, Kourin1996 commented
@Vuksan Thank you for your feedback! About `field 'blockHash' not found` issue, we need to merge https://github.com/0xPolygon/polygon-sdk/pull/59 first. If you don't have any issues except for this, should be ok. I will fix codes based on your feedback. Thank you :)

2021-06-14 04:02 UTC, Kourin1996 commented on e2e/framework/helper.go
> +			time.Sleep(time.Second)
It's for suppressing many calles in a moment.

2021-06-14 06:18 UTC, Kourin1996 commented on e2e/README.md
> +$ solc --bin e2e/sample.sol
I modified document

2021-06-14 06:18 UTC, Kourin1996 commented on e2e/framework/config.go
> +// SetIBFTDirPrefix callback sets prefix of IBFT directories
I updated comment

2021-06-14 06:18 UTC, Kourin1996 commented on e2e/discovery_test.go
>  				}
I fixed wrong sub test name

2021-06-14 06:19 UTC, Kourin1996 commented on e2e/broadcast_test.go
> +			}
I created `NewTestServers` helper function in e2e/framework/helper.go

2021-06-14 06:19 UTC, Kourin1996 commented on e2e/logs_test.go
> +	assert.GreaterOrEqual(t, len(res), numCalls/2)
I need to check implementation for log and fix if need. I will create another PR for this.

2021-06-14 06:20 UTC, Kourin1996 commented on e2e/logs_test.go
> +	}
I created NewTestServers helper function in e2e/framework/helper.go

2021-06-14 06:20 UTC, Kourin1996 commented on e2e/logs_test.go
> -
I added new assert

2021-06-14 06:20 UTC, Kourin1996 commented on e2e/ibft_test.go
> +		assert.NotNil(t, receipt)
I added this assertion

2021-06-14 06:21 UTC, Kourin1996 commented on e2e/transaction_test.go
> +	key, err := wallet.GenerateKey()
I fixed this and could test without `wallet.GenerateKey()`

2021-06-14 06:22 UTC, Kourin1996 commented on e2e/transaction_test.go
>  	}
I fixed the test and now it checks balance change for every case.

2021-06-14 06:41 UTC, Kourin1996 commented
@Vuksan I fixed codes based on your feedback. If you noticed something, please let me know. Thank you.

2021-06-14 12:37 UTC, Vuksan requested changes
👏  for applying suggestions. 
Let's just call `NewTestServers()` in several more places

2021-06-14 12:37 UTC, Vuksan commented on e2e/framework/helper.go
> +func NewTestServers(t *testing.T, num int, setConfig func(int, *TestServerConfig)) []*TestServer {
Why does `setConfig` function need to have the index parameter?
I don't see it used anywhere...

2021-06-14 12:37 UTC, Vuksan commented on e2e/logs_test.go
> +	}
I think there is no need for this `newLogsTestServer ` function. You should be able to call helper's `NewTestServers()` instead of this if I'm not mistaken...

2021-06-14 12:37 UTC, Vuksan commented on e2e/encoding_test.go
> +	receipt := srv.TxnTo(ctx, contractAddr, "setA1")
You can use helper's `NewTestServers()` here.

2021-06-14 12:37 UTC, Vuksan commented on e2e/transaction_test.go
> +		t.Fatal(err)
You can use helper's `NewTestServers()` here.

2021-06-14 12:37 UTC, Vuksan commented on e2e/transaction_test.go
> +	}
You can use helper's `NewTestServers()` here.

2021-06-14 12:37 UTC, Vuksan commented on e2e/transaction_test.go
> +		config.Premine(types.Address(senderAddr), preminedAmount)
Redundant type conversion
```suggestion
		config.Premine(senderAddr, preminedAmount)
```

2021-06-14 14:09 UTC, Vuksan approved these changes
Great job! 🚀

2021-06-15 08:51 UTC, lazartravica approved these changes
Recompiled, reran the tests and it all works excellent!

2021-06-15 10:27 UTC, zivkovicmilos approved these changes
[Test Results — Run all tests.pdf](https://github.com/0xPolygon/polygon-sdk/files/6654870/Test.Results.Run.all.tests.pdf)
All tests are passing, looks good to me.
Clean and efficient as always 💯

2021-06-15 11:43 UTC, merged