Add blockRangeLimit and batchRequestLimit JSON-RPC flags to help prevent node DDoS
0xPolygon/polygon-edge pull request #638
Opened 2022-07-12 16:24 UTC by dankostiuk

# Description

This PR introduces 2 new server flags that help prevent node DDoS:
`--json-rpc-block-range-limit` and `--json-rpc-batch-request-limit`

### Block Range Limit

During testing, we observed that a couple JSON-RPC requests that include block ranges could allow an attacker to use up all the resource on a particular node if they specify large ranges, essentially DDoS-ing that node. For example, the following request could take down any polygon-edge node running on a chain that consists of many blocks:
```
{"jsonrpc":"2.0","id":1,"method":"eth_getLogs","params":[{"fromBlock":"0","toBlock":"latest"}]}
```

To prevent such an attack, this PR enforces a default block range limit of 1000, optionally giving the node operator the ability to override this by specifying a value for `--json-rpc-block-range-limit` on their node's server command.

### Batch Request Limit

In addition to the above, since we currently don't have a limit for the allowed size of a batch JSON-RPC request body, attackers could spam RPC nodes with requests that contain thousands of batched requests, for example:
```
[
	{"jsonrpc": "2.0", "method": "eth_getBlockByNumber", "params": ["latest", true], "id": 0}, 
	{"jsonrpc": "2.0", "method": "eth_getBlockByNumber", "params": ["latest", true], "id": 1}, 
	{"jsonrpc": "2.0", "method": "eth_getBlockByNumber", "params": ["latest", true], "id": 2}, 
	{"jsonrpc": "2.0", "method": "eth_getBlockByNumber", "params": ["latest", true], "id": 3}, 
	{"jsonrpc": "2.0", "method": "eth_getBlockByNumber", "params": ["latest", true], "id": 4}, 
	{"jsonrpc": "2.0", "method": "eth_getBlockByNumber", "params": ["latest", true], "id": 5}, 
	{"jsonrpc": "2.0", "method": "eth_getBlockByNumber", "params": ["latest", true], "id": 6}, 
	{"jsonrpc": "2.0", "method": "eth_getBlockByNumber", "params": ["latest", true], "id": 7}, 
	{"jsonrpc": "2.0", "method": "eth_getBlockByNumber", "params": ["latest", true], "id": 8}, 
	{"jsonrpc": "2.0", "method": "eth_getBlockByNumber", "params": ["latest", true], "id": 9},
        ...
        {"jsonrpc": "2.0", "method": "eth_getBlockByNumber", "params": ["latest", true], "id": 99999},
]
```

Part of this PR also enforces a default batch request size of 20, optionally giving the node operator the ability to override this by specifying a value for `--json-rpc-batch-request-limit` on their node's server command.

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [ ] I have added the relevant labels
- [ ] I have updated the official documentation
- [x] I have added sufficient documentation in code

## Testing

- [x] I have tested this code with the official test suite
- [x] I have tested this code manually

### Manual tests

1. Run this branch on a node
2. Attempt to query with `{"jsonrpc":"2.0","id":1,"method":"eth_getLogs","params":[{"fromBlock":"0","toBlock":"1002"}]}` (this exceeds the default value of 1000). Observe error message in response.
3. Attempt to query with batch JSON-RPC request containing 25 entries (this exceeds the default of 20). Observe error message in response.
4. Add `--json-rpc-block-range-limit 1100` and `--json-rpc-batch-request-limit 30` to the server command on the same node and restart the node.
5. Attempt both queries from step 2. and 3. and observe that the node now responds with success responses.

# Documentation update

Will create a separate documentation PR once this PR is approved.

2022-07-16 05:32 UTC, Kourin1996 requested changes
Hello, Thank you for PR! The code looks good and it works completely. I've left some minor issues. It'd be cool if you could fix them

2022-07-16 05:32 UTC, Kourin1996 commented on command/server/server.go
> +		20,
It'd be great if you could define this value in constant 🙏

2022-07-16 05:32 UTC, Kourin1996 commented on command/server/server.go
> +		1000,
This is also

2022-07-16 05:32 UTC, Kourin1996 commented on jsonrpc/dispatcher.go
> +	batchLengthLimit uint64, blockRangeLimit uint64) *Dispatcher {
Could you define an argument per line if you need to define them in 2+ lines like this:

```suggestion
func newDispatcher(
        logger hclog.Logger,
        store JSONRPCStore,
        chainID uint64,
        priceLimit uint64,
	batchLengthLimit uint64,
	blockRangeLimit uint64,
) *Dispatcher {
```

2022-07-16 05:32 UTC, Kourin1996 commented on jsonrpc/dispatcher_test.go
> +		expectError bool
how about giving an error to be expected to return instead of flag?

2022-07-16 05:32 UTC, Kourin1996 commented on jsonrpc/dispatcher_test.go
> +			case 3:
I think using switch-case by test id is not best practice. All information that needs test can be given in `cases` data

2022-07-19 08:22 UTC, Kourin1996 requested changes

2022-07-19 08:22 UTC, Kourin1996 commented on jsonrpc/dispatcher_test.go
> +				assert.Nil(t, resp[3].Error)
Why not define these errors in cases?

2022-07-19 08:22 UTC, Kourin1996 commented on jsonrpc/dispatcher_test.go
> +				assert.Nil(t, resp[5].Error)
this is also

2022-07-19 08:22 UTC, Kourin1996 commented on jsonrpc/dispatcher_test.go
> +				assert.Nil(t, resp[3].Error)
Let me know if it's hard

2022-07-27 08:03 UTC, Kourin1996 approved these changes

2022-07-27 09:28 UTC, zivkovicmilos commented on command/server/server.go
> +		defaultConfig.JSONRPCBatchRequestLimit,
Did you mean `defaultConfig.JSONRPCBlockRangeLimit` here?

2022-07-27 09:32 UTC, zivkovicmilos approved these changes
Looks great 💯 

Thank you for the contribution, as always 🙏

2022-07-28 08:23 UTC, merged