[Feature] Datadog profiler
0xPolygon/polygon-edge pull request #707
Opened 2022-08-31 17:56 UTC by ZeljkoBenovic

This PR adds Datadog profiler into the codebase, so that it can be easily enabled on demand.
Profiler enables users to see profiles and tracing stats on their Datadog portal, but it requires some configuration of Datadog agent on the node. 

APM ( tracing ) should be enabled in Datadog agent configuration yaml file:
```
apm_config:

  enabled: true
  env: polygon-edge # this sets the environment name that will be shown on DD portal
```

To enable the profiler, a user must simply set `DD_PROFILING_ENABLED="True"` environment variable.
To set the IP and port that the DataDog agent, use `DD_AGENT_HOST` and `DD_TRACE_AGENT_PORT` environment variables.    
By default, it will try communicate with the agent on `localhost:8126`.

These env vars are now consistent with the DD doc https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/go/?tab=containers#configure-the-datadog-agent-for-apm

Additional parameters can be set by using env vars stated in the official Datadog doc https://docs.datadoghq.com/profiler/enabling/go/

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the relevant labels
- [ ] I have updated the official documentation
- [ ] I have added sufficient documentation in code

## Testing

- [ ] I have tested this code with the official test suite
- [x] I have tested this code manually

### Manual tests

Manual tests would require that the tester has access to Datadog portal.
Just set the `DD_ENABLE` env var, configure Datadog agent on the same node, and check Datadog portal if you can see your profile.

# Documentation update

Public doc will soon with the explanation on how to set this up will follow

# Additional comments

Fixes EDGE-764

2022-09-01 09:04 UTC, zivkovicmilos commented on server/server_metrics.go
> +func (s *Server) CloseDataDogProfiler() {
This shouldn't be an exported method, no need for that

2022-09-01 09:04 UTC, zivkovicmilos approved these changes
Looks great 💯

2022-09-02 14:52 UTC, ZeljkoBenovic commented on server/server_metrics.go
> +func (s *Server) CloseDataDogProfiler() {
unexported in be46b7199f54ae1cfd825dc31d9500004f810875

2022-09-02 20:00 UTC, Aleksao998 approved these changes
Code looks good to me, WHy are we having issues with CLAssistant first time seeing this

2022-09-02 20:01 UTC, Aleksao998 commented
I have read the CLA Document and I hereby sign the CLA

2022-09-07 11:32 UTC, Kourin1996 approved these changes

2022-09-07 11:32 UTC, Kourin1996 commented on server/server_metrics.go
> +	}()
Is there any reason to use defer here?

2022-09-07 11:32 UTC, Kourin1996 commented on server/server_metrics.go
> +	if os.Getenv("DD_ENABLE") == "" {
Why not check the value?

2022-09-16 11:34 UTC, epikichi commented on server/server_metrics.go
> +	if os.Getenv("DD_ENABLE") == "" {
In addition, we can use the variable `DD_PROFILING_ENABLED` for consistency and anticipation for a similar option in the Datadog Java Profiler. https://docs.datadoghq.com/profiler/enabling/java/?tab=environmentvariables

2022-09-16 20:00 UTC, epikichi requested changes

2022-09-16 20:00 UTC, epikichi commented on server/server_metrics.go
> +		// enable all profiles
- We can look to add `profiler.WithAgentAddr()`  for containerized solutions, as the default agent address in the profiler is implicitly `localhost:8126`.

Reference: [1.30.0](https://github.com/DataDog/dd-trace-go/releases/tag/v1.30.0)

This behavior does not hold true for the tracer, as it takes up the `DD_AGENT_HOST` env var. The release has further explanation on why they introduced the behavior.

2022-09-27 14:58 UTC, ZeljkoBenovic commented on server/server_metrics.go
> +	}()
You're right. Defers here makes no sense. Removed e0a262a286b1bb9df18d4811b4c28f8f359f0bd0

2022-09-27 14:59 UTC, ZeljkoBenovic commented on server/server_metrics.go
> +		// enable all profiles
Added the option to set IP and port, using env vars. `DD_PROF_IP` and `DD_PROF_PORT` in  e0a262a286b1bb9df18d4811b4c28f8f359f0bd0

2022-09-27 15:52 UTC, ZeljkoBenovic commented on server/server_metrics.go
> +		// enable all profiles
Changed env var to enable DD agent to `DD_PROFILING_ENABLED` and to define the agent host `DD_AGENT_HOST`

2022-09-27 16:20 UTC, vcastellm reviewed
The approach looks good in general, but I don't feel confortable with adding features using only env vars, I mean, ideally for me, this can be configurable in CLI params, config file and env vars, as we're using cobra that makes it really easy to do it.

2022-09-27 16:43 UTC, epikichi commented
> The approach looks good in general, but I don't feel confortable with adding features using only env vars, I mean, ideally for me, this can be configurable in CLI params, config file and env vars.

I agree as well. Let's include the CLI and config equivalent to this PR. @ZeljkoBenovic 

Ideally, we can offload the implementation to https://github.com/spf13/viper @zivkovicmilos :eyes:

2022-09-28 07:06 UTC, ZeljkoBenovic commented
@vcastellm The primary idea was not to clutter the UX with additional flags as DataDog is not a feature that is so commonly used as opposed to Prometheus for example.    
Secondly, we wanted to be aligned with their docs on how to setup things, for example https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/go/?tab=containers#configure-the-datadog-agent-for-apm where they are using env vars.     
Additionally, this is not a standalone feature, it still requires DataDog Agent installed and configured on the host ( or as a remote instance ) 

If you guys think that we need flags/config file parameters for this, it is very easy to add them.

2022-09-29 12:23 UTC, epikichi commented on server/server_metrics.go
> +		// enable all profiles
Looks good now. Thanks!

2022-09-29 12:26 UTC, epikichi approved these changes

2022-09-30 07:10 UTC, vcastellm approved these changes
LGTM

2022-10-06 10:24 UTC, merged