Get secret error handling fix
0xPolygon/polygon-edge pull request #781
Opened 2022-10-07 16:12 UTC by mrwillis

# Description

Please provide a detailed description of what was done in this PR

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

Please complete this section if any breaking changes have been made, otherwise delete it

# Checklist

- [ ] I have assigned this PR to myself
- [ ] I have added at least 1 reviewer
- [ ] I have added the relevant labels
- [ ] I have updated the official documentation
- [ ] I have added sufficient documentation in code

## Testing

- [ ] I have tested this code with the official test suite
- [ ] I have tested this code manually

### Manual tests

Please complete this section if you ran manual tests for this functionality, otherwise delete it

# Documentation update

Please link the documentation update PR in this section if it's present, otherwise delete it

# Additional comments

Please post additional comments in this section if you have them, otherwise delete it

2022-10-07 17:09 UTC, zivkovicmilos approved these changes
Looks great, again 💯

2022-10-10 07:01 UTC, JekaMas approved these changes

2022-10-11 01:28 UTC, epikichi requested changes
Thanks for the PR! 

I'm currently getting an error when trying to do a secrets initialization with both an existing and non-existing data directory `data`. Do you mind confirming? Below are the commands to reproduce the behavior on my end.
```
$ ./polygon-edge secrets init --data-dir data
unable to fetch secret (validator-key), unable to read secret from disk (data/consensus/validator.key), open data/consensus/validator.key: no such file or directory
```

2022-10-11 11:14 UTC, Kourin1996 approved these changes

2022-10-11 11:36 UTC, Kourin1996 requested changes

2022-10-11 11:36 UTC, Kourin1996 commented on consensus/ibft/signer/helper.go
> +	if !hasSecret {
This might work as expected because `HasSecret` throws error when the key is not saved.

2022-10-11 11:36 UTC, Kourin1996 commented on consensus/ibft/signer/helper.go
> +	hasSecret, err := manager.HasSecret(secrets.ValidatorBLSKey)
Same as above

2022-10-11 11:39 UTC, Kourin1996 requested changes
As @epikichi said before, `secrets init` command seems not to work. Can you check it?

2022-10-11 11:39 UTC, Kourin1996 commented on secrets/helper/helper.go
> +	}
When the key file doesn't exist, HasSecret throws error then `InitECDSAValidatorKey` just throws error as well.

2023-01-09 08:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/0xPolygon/polygon-edge?pullRequest=781) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/0xPolygon/polygon-edge?pullRequest=781) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/0xPolygon/polygon-edge?pullRequest=781) it.</sub>

2023-04-10 13:27 UTC, Stefan-Ethernal commented
Closing the PR as it is outdated since the codebase has changed a lot in a meantime.

2023-04-10 13:27 UTC, closed without merging