Add Dockerfile
0xPolygon/polygon-edge pull request #942
Opened 2022-11-21 00:40 UTC by scalalang2

# Description

I put a Dockerfile to compile polygon-edge with docker.
This can imporve the development productivity as we can create a sample [polygon-edge network locally](https://github.com/scalalang2/polygon-edge-docker-compose).

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

No Breaking changes

# Checklist

- [x] I have assigned this PR to myself
- [ ] I have added at least 1 reviewer
- [x] I have added the relevant labels
- [x] I have updated the official documentation
- [x] I have added sufficient documentation in code

## Testing

- [ ] I have tested this code with the official test suite
- [x] I have tested this code manually

### Manual tests

let's execute below command

```shell
docker build -t polygon-edge .
```

2022-11-21 00:41 UTC, scalalang2 commented
I have read the CLA Document and I hereby sign the CLA

2022-11-21 19:10 UTC, epikichi requested changes
Thanks for the contribution! This Dockerfile should help offer a familiar approach for those testing/developing in containerized environments.

@ZeljkoBenovic We have 3 separate Dockerfiles, including this one after acceptance. In the future, we can do something to [consolidate the one made for compose](https://github.com/0xPolygon/polygon-edge/blob/develop/docker/local/Dockerfile) with the proposed one in this PR, since they achieve similar goals.

2022-11-21 19:10 UTC, epikichi commented on Dockerfile
> +RUN cd /src && go build --tags musl -o polygon-edge main.go
Can we include the necessary `-ldflags`  to inject versioning context into the image builds as well? We can include them as `--build-args` if needed. 
- `-X "github.com/0xPolygon/polygon-edge/versioning.Version=${GITHUB_REF_NAME}"` 
- `-X "github.com/0xPolygon/polygon-edge/versioning.Commit=${GITHUB_SHA}"`

[Reference for flags](https://github.com/0xPolygon/polygon-edge/blob/f80b615edb8a69edea2a363b85a7f42c4a191251/.github/workflows/build.yml#L20)

2022-11-23 02:51 UTC, scalalang2 commented on Dockerfile
> +RUN cd /src && go build --tags musl -o polygon-edge main.go
thanks for feedback : ) I'll apply those changes soon.

2022-12-14 13:51 UTC, ZeljkoBenovic commented
Don't we already have [Dockerfile](https://github.com/0xPolygon/polygon-edge/blob/develop/docker/local/Dockerfile) in docker folder? In the same folder there is `docker-compose` as well.
Why is this `Dockerfile` different than the one we already have?

2022-12-15 02:20 UTC, scalalang2 commented
@ZeljkoBenovic 
At the time of writing this pull request, I couldn't find the `Dockerfile` since It's supposed to be on `root` directory.
There is no `Dockerfile` on root dir, so then, I thought that it doesn't exsit.

2022-12-15 02:21 UTC, scalalang2 commented
I agree that so I'll close this pr.

2022-12-15 02:21 UTC, closed without merging